// Generated by https://quicktype.io

import { Team } from "./team.interface";

export interface Temporal {
  teams: string[];
  color: string;
  _id:   string;
}

export interface TemporalTeam {
  teams: Team[];
  color: string;
  _id:   string;
}
