// Generated by https://quicktype.io

export interface Trial {
  _id:            string;
  name:           string;
  maxPoints:      number;
  pointsDecrease: number;
  maxTeams:       number;
  teamsAssignated:number;
  phase:          number;
  rated:          boolean;
  beginningPhase: boolean;
  endingPhase:    boolean;
}
